"""Render finsim Results to Markdown, CSV, or a console summary."""
from __future__ import annotations

from finsim import Results


def _m(x: float) -> str:
    """Format a money amount compactly (k/M), no currency symbol."""
    ax = abs(x)
    if ax >= 1_000_000:
        return f"{x/1_000_000:,.2f}M"
    if ax >= 1_000:
        return f"{x/1_000:,.0f}k"
    return f"{x:,.0f}"


def _pct(x: float | None) -> str:
    return "n/a" if x is None else f"{x*100:,.1f}%"


def _yr(x) -> str:
    return "never" if x is None else str(x)


def _metrics_lines(r: Results) -> list[str]:
    m = r.meta
    cur = m["currency"]
    regime = m["regime"].upper() + (" (auto)" if m["regime_auto"] else "")
    min_dscr = m["min_dscr"]
    dscr_s = "n/a" if min_dscr is None else f"{min_dscr:.2f}x"
    gap = "  ⚠️ financing gap" if m["min_cash"] < 0 else ""
    return [
        f"- **Tax regime:** {regime}",
        f"- **NPV** @ {_pct(m['discount_rate'])} (project FCF): **{_m(m['npv'])} {cur}**",
        f"- **IRR** (project): **{_pct(m['irr'])}**",
        f"- **Payback** (cumulative FCF ≥ 0): **{_yr(m['payback_year'])}**",
        f"- **P&L break-even** (net profit > 0): **{_yr(m['pl_breakeven_year'])}**",
        f"- **Min cash balance:** {_m(m['min_cash'])} {cur}{gap}",
        f"- **Min DSCR:** {dscr_s}",
        f"- **Total CAPEX / grant / equity:** {_m(m['total_capex'])} / {_m(m['total_grant'])} / {_m(m['equity'])} {cur}",
    ]


def render_markdown(r: Results) -> str:
    m = r.meta
    cur = m["currency"]
    out: list[str] = []
    out.append(f"# Financial projection — {m['name']}")
    out.append("")
    out.append(f"> Generated by **finsim** (planning aid, not advice). Currency: **{cur}**; "
               f"horizon {m['horizon_years']} yrs. RO tax rates mirror `knowledge/taxation.md` (2026).")
    out.append("")
    out.append("## Headline metrics")
    out += _metrics_lines(r)
    out.append("")

    # per-year table (line items as rows, years as columns)
    yrs = r.years
    header = "| Line (" + cur + ") | " + " | ".join(str(y) for y in yrs) + " |"
    sep = "|" + "---|" * (len(yrs) + 1)
    rows = [
        ("Revenue", r.revenue),
        ("OPEX", r.opex),
        ("EBITDA", r.ebitda),
        ("Depreciation", r.depreciation),
        ("Interest", r.interest),
        ("Tax", r.tax),
        ("Net profit", r.net_profit),
        ("Project FCF", r.project_fcf),
        ("Cash balance", r.cash_balance),
    ]
    out.append("## Year-by-year")
    out.append(header)
    out.append(sep)
    for label, series in rows:
        out.append(f"| {label} | " + " | ".join(_m(v) for v in series) + " |")
    # DSCR row (may contain None)
    out.append("| DSCR | " + " | ".join("–" if d is None else f"{d:.2f}x" for d in r.dscr) + " |")
    if any(v > 0 for v in r.dividends_net):
        out.append("| Dividends (net) | " + " | ".join(_m(v) for v in r.dividends_net) + " |")
    out.append("")
    out.append("## Caveats")
    out.append("- Amounts exclude VAT (assumed pass-through; CAPEX VAT recoverable with a timing lag).")
    out.append("- Payroll uses CAS 25% + CASS 10% + 10% income tax (employee) and CAM 2.25% (employer); "
               "min-wage tax reliefs and CASS-on-dividends are not modelled.")
    out.append("- Grants reduce the depreciation base pro-rata (toggle per grant); CIT uses simple loss carry-forward.")
    out.append("- Re-verify rates against `knowledge/taxation.md` and `knowledge/open-questions.md` before relying on this.")
    out.append("")
    return "\n".join(out)


def render_console(r: Results) -> str:
    m = r.meta
    lines = [f"=== {m['name']} ({m['currency']}, {m['horizon_years']}y) ==="]
    lines += [ln.replace("**", "").replace("- ", "  ") for ln in _metrics_lines(r)]
    return "\n".join(lines)


def render_csv(r: Results) -> str:
    import csv
    import io
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["line"] + r.years)
    for label, series in [
        ("revenue", r.revenue), ("opex", r.opex), ("ebitda", r.ebitda),
        ("depreciation", r.depreciation), ("interest", r.interest),
        ("principal", r.principal), ("tax", r.tax), ("net_profit", r.net_profit),
        ("project_fcf", r.project_fcf), ("cash_balance", r.cash_balance),
    ]:
        w.writerow([label] + [round(v, 2) for v in series])
    return buf.getvalue()
